### ISSUE TITLE
Error in Net.py

### ISSUE THREAD

**Issue by dhavalkvaria** [patmalcolm91/SumoNetVis#16] opened 2020-04-24 06:47 UTC
File "D:/SHARE/SumoNetVis-master/SumoNetVis-master/test.py", line 4, in <module>
    net = SumoNetVis.Net("area.net.xml")
  File "D:\SHARE\SumoNetVis-master\SumoNetVis-master\SumoNetVis\Net.py", line 624, in __init__
    lane = _Lane(laneObj.attrib)
  File "D:\SHARE\SumoNetVis-master\SumoNetVis-master\SumoNetVis\Net.py", line 141, in __init__
    self.id = attrib["id"]
KeyError: 'id'

Please help me to resolve this error

**Comment by patmalcolm91** [comment] 2020-04-24 07:05
It appears as if there is a lane object in your net file which does not have an "id" attribute. According to the [Sumo network file specification](https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html#stop_offsets), this is a required attribute, so should always be present, at least if you created the network with Netedit or Netconvert. How was your network file generated? Are you able to open the file in Netedit without errors?

**Comment by dhavalkvaria** [comment] 2020-04-24 07:18
Dear Sir,
Yes, sir, the file can be open with net edit ant able to run it in sumo.

I am attaching the network file here.

Please help.

*:)*



*Thanks & Best
Regards.----------------------------------------------------------------------------------------Dhaval
varia*
*(9924343883)*

**Comment by patmalcolm91** [comment] 2020-04-24 07:27
It looks like the file you attached to your email response didn't come through in GitHub. Instead of attaching the file, you can try copying the contents of the file (by opening in Notepad) and pasting inside code fences (\`\`\`code here\`\`\`), like so:

```
contents of file
```

**Comment by dhavalkvaria** [comment] 2020-04-24 08:03
`<net version="1.3" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

<edge id=":0_0" function="internal">
        <lane id=":0_0_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="22.22" length="0.10" shape="2534.77,924.09 2534.80,924.10"/>
    </edge>
    <edge id=":10_0" function="internal">
        <lane id=":10_0_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="25.00" length="0.30" shape="1241.93,2210.73 1241.86,2210.44"/>
    </edge>
    <edge id=":10_1" function="internal">
        <lane id=":10_1_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="3.65" length="2.34" shape="1241.93,2210.73 1242.46,2209.39 1243.16,2208.83"/>
    </edge>
    <edge id=":10_4" function="internal">
        <lane id=":10_4_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="3.65" length="2.34" shape="1243.16,2208.83 1244.02,2209.06 1245.06,2210.06"/>
    </edge>
    <edge id=":10_2" function="internal">
        <lane id=":10_2_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="25.00" length="0.30" shape="1244.99,2209.77 1245.06,2210.06"/>
    </edge>
    <edge id=":10_3" function="internal">
        <lane id=":10_3_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="3.65" length="2.34" shape="1244.99,2209.77 1244.46,2211.11 1243.76,2211.67"/>
    </edge>
    <edge id=":10_5" function="internal">
        <lane id=":10_5_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="3.65" length="2.34" shape="1243.76,2211.67 1242.90,2211.44 1241.86,2210.44"/>
    </edge>
    <edge id=":100_0" function="internal">
        <lane id=":100_0_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="6.49" length="9.03" shape="1239.56,2199.63 1238.70,2197.30 1237.31,2195.81 1235.37,2195.17 1232.90,2195.36"/>
    </edge>
    <edge id=":100_1" function="internal">
        <lane id=":100_1_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="27.78" length="14.94" shape="1239.56,2199.63 1238.83,2195.96 1238.21,2192.28 1237.69,2188.58 1237.27,2184.87"/>
    </edge>
    <edge id=":100_2" function="internal">
        <lane id=":100_2_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="3.65" length="2.34" shape="1239.56,2199.63 1240.09,2198.28 1240.79,2197.73"/>
    </edge>
    <edge id=":100_10" function="internal">
        <lane id=":100_10_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="3.65" length="2.34" shape="1240.79,2197.73 1241.65,2197.95 1242.68,2198.96"/>
    </edge>
    <edge id=":100_3" function="internal">
        <lane id=":100_3_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="6.58" length="9.30" shape="1247.33,2192.26 1244.86,2193.13 1243.26,2194.54 1242.53,2196.48 1242.68,2198.96"/>
    </edge>
    <edge id=":100_4" function="internal">
        <lane id=":100_4_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="14.78" shape="1247.33,2192.26 1232.90,2195.36"/>
        <lane id=":100_4_1" index="1" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="14.78" shape="1246.68,2189.13 1232.20,2192.24"/>
    </edge>
    <edge id=":100_6" function="internal">
        <lane id=":100_6_0" index="0" allow="private emergency authority army vip passenger hov taxi tram rail_urban rail rail_electric rail_fast ship" speed="7.13" length="11.92" shape="1246.68,2189.13 1242.79,2189.54 1239.92,2188.97 1238.08,2187.41 1237.27,2184.87"/>
    </edge>`

**Comment by patmalcolm91** [comment] 2020-04-24 08:10
I don't see anything that should cause any problems in that part of the net file. I just had another idea, though. Do you have any stop offsets defined in the network? You can check this by searching the text of your file for ```stopOffset```. If so, can you test your network with the code from the [stoplines branch](https://github.com/patmalcolm91/SumoNetVis/tree/stoplines)?

**Comment by dhavalkvaria** [comment] 2020-04-24 08:27
Dear sir,

Not able to workout.

Is it possible for you to view the file,if I send the complete network file
to you through email?

Your help is highly appreciated. Please help.

**Comment by patmalcolm91** [comment] 2020-04-24 08:33
Yes, you can send me the file, however I don't want to post my email address here. Instead, you can upload it to a file sharing site (such as google drive, dropbox, or https://www.file.io) and provide the share link.

**Comment by dhavalkvaria** [comment] 2020-04-24 09:20
Thank you for the support, sir.

Please find the file in the link below :
https://drive.google.com/file/d/1pLxxBoSJRBgN8rXx9nuGvRfdLEMG2E7e/view?usp=sharing


*:)*



*Thanks & Best
Regards.----------------------------------------------------------------------------------------Dhaval
varia*
*(9924343883)*

**Comment by patmalcolm91** [comment] 2020-04-24 09:50
The problem is being caused by the ```<param>``` tags in the network file being misinterpreted as lanes. As I suspected, this is resolved by a change I made in the stoplines branch, which I have just merged into the master branch. If you downloaded the code using git, you can now do a ```git pull``` to get the changes, or you can re-download the code from GitHub. Thanks for your interest in the project, and let me know if you have any further issues!

**Closed by patmalcolm91** 2020-04-24 09:50 UTC

**Comment by dhavalkvaria** [comment] 2020-04-24 10:02
Thank you for your response.

Its working now. Thank you once again sir.
